name: Build packages
on:
  push:
    branches:
      - packages
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Build packages
      id: create_tag
      run: |
        ls -l
        ls -R
        git checkout packages
        ls -l
        version=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
        echo "::set-output name=tag::${version}"
        cat << EOF > entrypoint.sh
        cd /build
        useradd builduser -m
        passwd -d builduser
        pacman -Syu --noconfirm --needed sudo base-devel
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser /build
        chown -R builduser:builduser /root
        for i in apple-ibridge-dkms-git apple-t2-audio-config
        do cd $i
        ls -l
        sudo -u builduser bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
        cd /build
        done
        EOF
        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
        zip packages.zip */*.pkg.tar.*

    - name: Upload Packages Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mbp-packages-${{ steps.create_tag.outputs.tag }}
        path: ${{ github.workspace }}/packages.zip

    - name: Create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false

    - name: Add packages to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/packages.zip
        asset_name: mbp-packages-${{ steps.create_tag.outputs.tag }}.zip
        asset_content_type: application/zip
