name: Build packages
on:
  push:
    branches:
      - packages
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Build packages
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        echo '[mbp]
        Server = https://dl.t2linux.org/archlinux/\$repo/\$arch' >> /etc/pacman.conf
        pacman-key --init
        curl -o key.asc https://dl.t2linux.org/archlinux/key.asc
        pacman-key --add key.asc
        pacman-key --lsign 7F9B8FC29F78B339
        useradd builduser -m
        passwd -d builduser
        pacman -Syu --noconfirm --needed sudo base-devel linux-mbp linux-mbp-headers
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser /build
        cd /build/apple-t2-audio-config
        ls -l
        sudo -u builduser bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
        cd /build/apple-ibridge-dkms-git
        ls -l
        sudo -u builduser bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
        EOF
        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
        ls -l . apple-ibridge-dkms-git apple-t2-audio-config
        sudo zip packages.zip */*.pkg.tar.*
        
    - name: generate tag
      id: tag
      run: |
        count=$(git rev-list --count HEAD)
        hash=$(git rev-parse --short HEAD)
        echo "::set-output name=tag::r${count}.${hash}"
        
    - name: Print sha512sums
      run: sha512sum */*.pkg.tar.*

    - name: Upload Packages Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mbp-packages-${{ steps.tag.outputs.tag }}
        path: ${{ github.workspace }}/packages.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
              ${{ github.workspace }}/*/*.pkg.tar.*
        tag_name: ${{ steps.tag.outputs.tag }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
